// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbkwfjydneknqnumaswy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJia3dmanlkbmVrbnFudW1hc3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4Njg5NjAsImV4cCI6MjA4NzQ0NDk2MH0._v5yZ7-NXdJAxP8wXRtcfz5jGdwVwfZuQAS2LtyIPkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});